'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.8762
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Class DesignSettings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SmartDeviceCore.DesignSettings", GetType(DesignSettings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property BackColor() As String
            Get
                Return ResourceManager.GetString("BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  166,58,76 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF1BackColor() As String
            Get
                Return ResourceManager.GetString("btnF1BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  67,86,175 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF2BackColor() As String
            Get
                Return ResourceManager.GetString("btnF2BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  72,114,97 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF3BackColor() As String
            Get
                Return ResourceManager.GetString("btnF3BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  166,158,76 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF4BackColor() As String
            Get
                Return ResourceManager.GetString("btnF4BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ContentColor() As String
            Get
                Return ResourceManager.GetString("ContentColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  240,320 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DefaultWindowSize() As String
            Get
                Return ResourceManager.GetString("DefaultWindowSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  33,33,33 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property PrimaryTextColor() As String
            Get
                Return ResourceManager.GetString("PrimaryTextColor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
