'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DesignSettings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Moca.DesignSettings", GetType(DesignSettings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  63, 81, 181 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ActionButtonBackColor() As String
            Get
                Return ResourceManager.GetString("ActionButtonBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ActionButtonForeColor() As String
            Get
                Return ResourceManager.GetString("ActionButtonForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property BackColor() As String
            Get
                Return ResourceManager.GetString("BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  229,0,0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF1BackColor() As String
            Get
                Return ResourceManager.GetString("btnF1BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF1ForeColor() As String
            Get
                Return ResourceManager.GetString("btnF1ForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0,0,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF2BackColor() As String
            Get
                Return ResourceManager.GetString("btnF2BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF2ForeColor() As String
            Get
                Return ResourceManager.GetString("btnF2ForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0,192,0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF3BackColor() As String
            Get
                Return ResourceManager.GetString("btnF3BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  51,51,51 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF3ForeColor() As String
            Get
                Return ResourceManager.GetString("btnF3ForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,215,0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF4BackColor() As String
            Get
                Return ResourceManager.GetString("btnF4BackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  51,51,51 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnF4ForeColor() As String
            Get
                Return ResourceManager.GetString("btnF4ForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  212,208,200 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnLogoffBackColor() As String
            Get
                Return ResourceManager.GetString("btnLogoffBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  51,51,51 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property btnLogoffForeColor() As String
            Get
                Return ResourceManager.GetString("btnLogoffForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ContentColor() As String
            Get
                Return ResourceManager.GetString("ContentColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  240,320 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DefaultWindowSize() As String
            Get
                Return ResourceManager.GetString("DefaultWindowSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  232,17,35 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ErrorBackColor() As String
            Get
                Return ResourceManager.GetString("ErrorBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  32,32,32 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ErrorForeColor() As String
            Get
                Return ResourceManager.GetString("ErrorForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  173,7,74 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property FocusColor() As String
            Get
                Return ResourceManager.GetString("FocusColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  0, 120, 215 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property FormBorderColor() As String
            Get
                Return ResourceManager.GetString("FormBorderColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  230, 230, 230 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property InformationBackColor() As String
            Get
                Return ResourceManager.GetString("InformationBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  26, 26, 26 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property InformationForeColor() As String
            Get
                Return ResourceManager.GetString("InformationForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  33,33,33 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property PrimaryTextColor() As String
            Get
                Return ResourceManager.GetString("PrimaryTextColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  118,185,237 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property QuestionBackColor() As String
            Get
                Return ResourceManager.GetString("QuestionBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  64, 64, 64 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property QuestionForeColor() As String
            Get
                Return ResourceManager.GetString("QuestionForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  255,211,92 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property WarningBackColor() As String
            Get
                Return ResourceManager.GetString("WarningBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  145, 111, 53 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property WarningForeColor() As String
            Get
                Return ResourceManager.GetString("WarningForeColor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
