'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.8762
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Class MyFormValidate
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Moca.MyFormValidate", GetType(MyFormValidate).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  255,255,255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DefalutControlBackColor() As String
            Get
                Return ResourceManager.GetString("DefalutControlBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  51, 51, 51 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DefalutControlForeColor() As String
            Get
                Return ResourceManager.GetString("DefalutControlForeColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  242, 222, 222 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ErrorControlBackColor() As String
            Get
                Return ResourceManager.GetString("ErrorControlBackColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  185, 74, 72 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property ErrorControlForeColor() As String
            Get
                Return ResourceManager.GetString("ErrorControlForeColor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
